USE tradescope;


INSERT INTO tbl_currencies (code, country) VALUES (N'USD', N'United States')
INSERT INTO tbl_currencies (code, country) VALUES (N'EUR', N'Eurozone')
INSERT INTO tbl_currencies (code, country) VALUES (N'JPY', N'Japan')
INSERT INTO tbl_currencies (code, country) VALUES (N'GBP', N'United Kingdom')
INSERT INTO tbl_currencies (code, country) VALUES (N'CHF', N'Switzerland')
INSERT INTO tbl_currencies (code, country) VALUES (N'CAD', N'Canada')
INSERT INTO tbl_currencies (code, country) VALUES (N'AUD', N'Australia')
INSERT INTO tbl_currencies (code, country) VALUES (N'NZD', N'New Zealand')
INSERT INTO tbl_currencies (code, country) VALUES (N'BRL', N'Brazil')
INSERT INTO tbl_currencies (code, country) VALUES (N'MXN', N'Mexico')
INSERT INTO tbl_currencies (code, country) VALUES (N'ARS', N'Argentina')
INSERT INTO tbl_currencies (code, country) VALUES (N'CLP', N'Chile')
INSERT INTO tbl_currencies (code, country) VALUES (N'COP', N'Colombia')
INSERT INTO tbl_currencies (code, country) VALUES (N'PEN', N'Peru')
INSERT INTO tbl_currencies (code, country) VALUES (N'ZAR', N'South Africa')
INSERT INTO tbl_currencies (code, country) VALUES (N'TRY', N'Turkey')
INSERT INTO tbl_currencies (code, country) VALUES (N'PLN', N'Poland')
INSERT INTO tbl_currencies (code, country) VALUES (N'CZK', N'Czech Republic')
INSERT INTO tbl_currencies (code, country) VALUES (N'HUF', N'Hungary')
INSERT INTO tbl_currencies (code, country) VALUES (N'SEK', N'Sweden')
INSERT INTO tbl_currencies (code, country) VALUES (N'NOK', N'Norway')
INSERT INTO tbl_currencies (code, country) VALUES (N'DKK', N'Denmark')
INSERT INTO tbl_currencies (code, country) VALUES (N'ILS', N'Israel')
INSERT INTO tbl_currencies (code, country) VALUES (N'SAR', N'Saudi Arabia')
INSERT INTO tbl_currencies (code, country) VALUES (N'AED', N'United Arab Emirates')
INSERT INTO tbl_currencies (code, country) VALUES (N'CNY', N'China')
INSERT INTO tbl_currencies (code, country) VALUES (N'HKD', N'Hong Kong')
INSERT INTO tbl_currencies (code, country) VALUES (N'SGD', N'Singapore')
INSERT INTO tbl_currencies (code, country) VALUES (N'KRW', N'South Korea')
INSERT INTO tbl_currencies (code, country) VALUES (N'INR', N'India')
INSERT INTO tbl_currencies (code, country) VALUES (N'IDR', N'Indonesia')
INSERT INTO tbl_currencies (code, country) VALUES (N'MYR', N'Malaysia')
INSERT INTO tbl_currencies (code, country) VALUES (N'PHP', N'Philippines')
INSERT INTO tbl_currencies (code, country) VALUES (N'THB', N'Thailand')